version: '2'
services:
  metricstore:
    env_file: .env
    image: postgres:9.5
    # name: ${METRICSTORE_CONTAINER_ID}
    expose:
    - "${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    # ports:
    # - "${METRICSTORE_PORT_MAPPING}:${DB_PORT}"

  datasource:
    # name: ${DATASOURCE_CONTAINER_ID}
    build:
      context: lib/datasource
      args:
        ES_PORT: $ES_PORT
    env_file: .env
    image: sarjitsu:elasticsearch
    ports:
    - "${DATASOURCE_PORT_MAPPING}:${ES_PORT}"

  frontend:
    # name: ${FRONTEND_CONTAINER_ID}
    build:
      context: lib/frontend
      args:
        GRAFANA_PORT: $GRAFANA_PORT
    env_file: .env
    image: sarjitsu:grafana
    ports:
    - "${FRONTEND_PORT_MAPPING}:${GRAFANA_PORT}"
    links:
     - metricstore
     - datasource
    depends_on:
     - metricstore
     - datasource

  middleware:
    # name: ${MIDDLEWARE_CONTAINER_ID}
    build:
      context: lib/middleware
      args:
        MIDDLEWARE_PORT: $MIDDLEWARE_PORT
    env_file: .env
    image: sarjitsu:api
    ports:
    - "${MIDDLEWARE_PORT_MAPPING}:${MIDDLEWARE_PORT}"
    depends_on:
     - datasource
    links:
     - datasource
    # command: sh /srv/scripts/post-run-web.sh

  web:
    # name: ${BACKEND_CONTAINER_ID}
    build:
      context: lib/backend
      args:
        BACKEND_SERVER_PORT: $BACKEND_SERVER_PORT
    env_file: .env
    image: sarjitsu:backend
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    ports:
    - "${BACKEND_PORT_MAPPING}:${BACKEND_SERVER_PORT}"
    depends_on:
     - metricstore
     - datasource
     - frontend
     - middleware
    links:
     - metricstore
     - datasource
     - frontend
     - middleware
