apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "9702"
    port: 9702
    protocol: TCP
    targetPort: 3000
  selector:
    service: frontend
status:
  loadBalancer: {}
