apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "9702"
    port: 9702
    targetPort: 3000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
