apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: frontend
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: lib/frontend/
    git:
      ref: komposed
      uri: https://github.com/arcolife/sarjitsu.git
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: GRAFANA_PORT
        value: "3000"
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
