apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: metricstore
  name: metricstore
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: metricstore:metricstore_official
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: lib/metricstore/
    git:
      ref: non-root
      uri: https://github.com/arcolife/sarjitsu.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
