apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: middleware
  name: middleware
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: middleware:api
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: lib/middleware/
    git:
      ref: master
      uri: https://github.com/arcolife/sarjitsu.git
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: MIDDLEWARE_PORT
        value: "5000"
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
