apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: middleware
  name: middleware
spec:
  ports:
  - name: "9703"
    port: 9703
    targetPort: 5000
  selector:
    io.kompose.service: middleware
status:
  loadBalancer: {}
