apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nginx:proxy
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: lib/proxy/
    git:
      ref: master
      uri: https://github.com/arcolife/sarjitsu.git
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: PROXY_PORT
        value: "8001"
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
