apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "9705"
    port: 9705
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
